# Generated by Django 2.0 on 2019-06-07 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
